version: '3.8'

services:
    dev:
        container_name: rm-html-nestjs-docker-deb
        image: rm-html-nestjs-docker-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
            - ${APP_PORT}:${APP_PORT}
            - 9229:9229
        networks:
            - rm-nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    prod:
        container_name: nestjs_api_prod
        image: nestjs-api-prod:1.0.0
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command: npm run start:prod
        ports:
            - ${APP_PORT}:${APP_PORT}
            - 9229:9229
        networks:
            - rm-nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped

networks:
    rm-nesjs-network: